on: workflow_call

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Changelog
        run: |
          git config --global user.email "sheep@taskany.org"
          git config --global user.name "Taskany Sheep"
          npx @taskany/release@latest
          npm version $(cat version) --git-tag-version false
          git tag v$(cat version)
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup packages
        run: npm ci
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm publish
      - name: Push
        run: |
          git config --global user.email "sheep@taskany.org"
          git config --global user.name "Taskany Sheep"
          git add .
          git commit -n -m "chore: release $(cat version)"
          git push --no-verify origin main
          git push --no-verify origin --tags
      - name: GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create v$(cat version) --title "Release $(cat version)" -F .release_notes/$(cat version).md
