name: Publish

on:
  workflow_call:
  pull_request_target:
    types:
      - closed
    paths:
      - '.release_notes/**'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/checkout.yml
      - uses: ./.github/workflows/npm_publish.yml
      - uses: ./.github/workflows/gh_release.yml
