name: Publish

on:
  pull_request_target:
    types:
      - closed
    paths:
      - .release_notes/**

jobs:
  npm_publish:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/npm_publish.yml
  gh_release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/gh_release.yml
