on: workflow_call

jobs:
  release_pr:
    name: Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Auth
        uses: actions/create-github-app-token@v1
        id: auth
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}
      - name: Setup packages
        run: npm ci
      - name: Changelog
        run: |
          git config --global user.email "sheep@taskany.org"
          git config --global user.name "Taskany Sheep"
          npx @taskany/release@latest
          npm version $(cat version) --git-tag-version false
          git checkout -b releases/$(cat version)
          git add .
          git commit -n -m "chore: release $(cat version)"
          git push --no-verify origin releases/$(cat version)
      - name: Pull Request
        id: pr
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          gh pr create --title "Release $(cat version)" --label release -F .release_bot/body
          
